//
// Created by Niccolò Niccoli on 18/02/2023.
//

#ifndef KERNEL_IMAGE_PROCESSING_DEFINITIONS_H
#define KERNEL_IMAGE_PROCESSING_DEFINITIONS_H

#define TILE_WIDTH 16
#define MASK_WIDTH 15
#define BLOCK_WIDTH (TILE_WIDTH + MASK_WIDTH - 1)
#define RUN_CUDA 0
#define RUN_OMP 1
#define RUN_SEQ 1

#endif //KERNEL_IMAGE_PROCESSING_DEFINITIONS_H
