//
// Created by Niccolò Niccoli on 08/02/2023.
//

#ifndef KERNEL_IMAGE_PROCESSING_PARALLELCONVOLUTION_H
#define KERNEL_IMAGE_PROCESSING_PARALLELCONVOLUTION_H
#endif //KERNEL_IMAGE_PROCESSING_PARALLELCONVOLUTION_H
